language: ruby
rvm:
- 2.3.4
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id:
    secure: LIJePE+gHsWVwHMZi09XOvAgLwo3h76ZqU4RwEyULm4oFA4ANZuwp2NV1uUl+rtbPL8msF9Ts4IA2t/44CD/kVaE32Xng+y+qal3JoYQm4S/HyJsF1S6UfixIh5mzwJ6fDVg5dCgIKdlaPuVf+ESzlISpmfBibPbCsRzQY4V5zKycP6parzKHAekOw602AVVCj12Do2RuSLLIurUflLPRSuY2utG+zTNCAArLYXbfNyNFpUz6o9KjvBd+YtvJE5VTy0Re7Ygs7hhz61R+cSS0y/pwUXrwsWyQXb2EleRnuZkdFhKELxzTgEpPNZ0x4NTw7V0XP6RZTpEZ30n1FSa8n4G2zrLjf0+F2KAFf31EZyAm5MV2cc3jt4eP8+L2zJFpFafXj4j14dBT/2mTnGPj1VA2H4fD66jCqdgPV570sfqrMRS0UrbCpMK4bIimJYpsXHBAOg+xLm26ZRPyNZvZBSE5KQjPHEdE8mpi8WywapBTG7wisyNoyXAoq4lafuDcvjAD3o4Yi1cIuMT28SwFkoIJkgwKqlSKmDW64NdQl9BziusYG7SjAC6QwogPXvxRA0+7RxAPUTeD0Besz6divpUWUOPUQz3PcCqaOSW/spXKgjHYVt2tm+GztUMehKp9zxBjT5Qq0XObGr15i2N8gPL5rqNDBxQZndxLwA91g8=
  bucket: blog.gonad.org.uk
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  secret_access_key:
    secure: wNMez6MkCuAC3j4GRRar+4ZePvDeKEGs6Sr/YqxfSFtJBmg+7acsgzzDC9O2UE+p0xTeL6qK9WnG+SSmtIkndC0Ri2R3xu8FoY9MTasNt+fE+ibJT3BTimDZxKq7uXIkbqRulikJwZThaMn4cNAhrHTOY0jf+vOpAaFs3lUFUZ1lLctyTOYDFHIKaRA25u2eNWXRyaoY+McP3VybWYwZH9qxiB6Hu29DZXZe3nL/f4y1d/s6/jDtBOth7F3lpVBEgRgHoDgPpE3duSq02UVZrmJ9nlFsLzSpzWGlrZfsLTQPB3AwWLKKE44y9TXyseUfK586rBIP0tXdXHzGXGvrU+06sEcJ7HTHNwBzOBkuYpSrhRzZo1I4inoh7sXbfR4ITbery4BYwPoKMASuEdsMNrSjr9tQjELzQE2hsRiOUQrQRcXrWPRBay2wFaB8vZ0zmV91azoU7MZUg4IhsSdK69QljY/vLKk0BSLLgGrFM7QSeZFi6B4AQ7XunrG5ODjR6eCxrhvTyRVc17n7EoS244WnTSTKPRu3rWl9yQahcLEkGGr8RCM3DaoKYRPuRtqltY0KnJgThW2E+XKqdply74Z61fwcAuafjKhbB4Xn2whMx3Wbc+hFiZVorbHKXfEUdXMtlVgvNrgEmu9wPNw+eZmA8L88zVMl/OsH6njBH7A=
