language: ruby
rvm:
- 2.3.4
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id:
    secure: EtK+Kj+XTjJNQL8Fy4E4Jr+HcasliFwaQRSdgLPmaCvUxstbifoe/ulHnH+xQrKm5oSvQW3bExSRAJfh6/rvIT3pisILKxHJaIIRrR/mTnXjDmByuT/jYcjsag8bZhtpb6P+nGVtLSYfu6Bw2hyio7MBZ1SSb+ZuSBrB8xCAYdEkYO9gmK0OAH9Yy+zxuc8a9xNPYeHuyPS1HQB8XBY/ZR84wnpGmM+qxnkm47BpxtSXvJlGI7sIUNil7jDVw1NepuIYagELJi10cMstGsD/wU4LgbLXTSqaPNu5kmbNyepM60XWQRwHl9RgoDm+WVRa7juyY1TUOI0B4F+xPuN25QFaHhTCiqRcqiwYWsk2k2PVbRigY5Ztdk2v6lH4G2ApXWCeqF4Fq+uIUOKTtYqQQ1VKqakLOpDkfuOikldVrIjXZwYp/yobp0QDnxtVQsRZ1gitjwrib6WupjShUvYsNfv5NcFbT3DgRcTzAQIXXdagpXLNYc3pg8rR39onYy9/LfkdGZt2+DrheXQKFr6jUoggjTG5E/N+9QpkXx8i970ZIIvP+L3BTBp8qFpUszf0/AeAuZexIzMlEfpbG8IUcqyqTfP/p02eZLcEPpM6tWOwisEeyJUQX8Ggu8XRJXJZPPUO6pn4oUBSS1MGw6ROqwF6+n1zkZFzVFokZkNUzgo=
  bucket: blog.gonad.org.uk
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  secret_access_key:
    secure: bxuqz+obWS7sTEy02FuuMUIQE1RlmrmZtNuUXrlN+dV8m2maGpe+wNnE0kEZMe7w8fosZPAebRhTBj1/E/fg/JUzhb8OTJJ2UhInIGAE4KcGyi3jKxCpa8NqT1KAvT3Dt0BL1NpujXng1Rseyq0qxle0uQKx6ubrgihmnMHMwgTcE6/Dool4gzZa/34hs7U5PdgV1H78Q+MF16HKd5sMQATG6H41mBwffshiHTDGi2pBNLOhSfdG8nNsmp6H93m5cvFlegfeWJGYEkGfFFth/qomwAem+KmemtJnzGtAl+z7t58m8FWaRP5lm8YeA3n1mCpFS2f6dE1SWBWJ6+GMRjbLyMKb9c+AUzRFRcMtou8k3jyu00Kq1JICxw2byrVeh8nftt+bPlvpNaOVUNbUzyqUpB12oSW4/33hxOp+r2QVYyqHVar1xrG5Xo7oQfiJs4yNoofS9AYgjPMTrrsmUnIo3fAzkWuP3IRgI6FiWnUTapmuql5MBS+2T1IIwqQkMWUhqhGL/rSM4LHOva28RvIrH9kZBY2y7mZiNm4FIhNt21O+G621jgSZFoDcZC3+IaxlNuoZ5wIxMg+55SWvxJuBsJd2flkFQYI6G7rW/v/7Zm0E4/s0/APaHkUtGmY5amZBEn0Cv9aotydZkW4BwFIZZx7b1ABlf53j51hLVnQ=
