#
###################################
# Site wide configuration
####################################
#
title: John's Linux Stuff
email: john@gonad.org.uk
description: Useful solutions for common problems which I have picked up, can never remember and therefore want to keep in one place for reference.
url: http://blog.gonad.org.uk

host: 172.16.36.24
#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title/
post_dirs: false
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: John's Linux Stuff
  avatar: John-190-250.jpg
  job: "Tips and Tricks from the coalface"
  bio: "Useful solutions for common problems which I have picked up, can never remember and therefore want to keep in one place for reference"
  email: john@gonad.org.uk
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jehudson
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
